- java/java8/Dockerfile
See https://github.com/googleapis/google-auth-library-java/pull/222
> Add Python 3 to Java8 image for releasetool reporter

- python/cloud-devrel-kokoro-resources/python-base/Dockerfile
tested with https://github.com/GoogleCloudPlatform/python-docs-samples/blob/automl-edge-predict-test/vision/automl/edge_container_predict/automl_vision_edge_container_predict_test.py
> add docker to python-base

- node/10-user/Dockerfile
- node/8-user/Dockerfile
> node: add gcloud to 8-user and 10-user

- python/googleapis/python-multi/Dockerfile
Required to run tests for this Sample: GoogleCloudPlatform/python-docs-samples#2554
> Updating to install graphviz

- python/googleapis/python-multi/Dockerfile
For testing connection samples for MS SQL server in python-docs-samples
> Add SQL Server dependencies to Dockerfile

- .kokoro/build.sh
- README.md
- go/cloudbuild.yaml
- java/cloudbuild.yaml
- node/cloudbuild.yaml
- python/cloudbuild.yaml
- python/googleapis/python-multi/Dockerfile
- ruby/cloudbuild.yaml
> Modify cloudbuild.yaml to be compatible with GitHub triggers

- ruby/ruby-multi/Dockerfile
Adding FreeTDS, which is a dependency to connect to SQL Server, so that tests for this sample can pass: https://github.com/GoogleCloudPlatform/ruby-docs-samples/pull/569
> Added FreeTDS to ruby-multi Dockerfile

- go/README.md
- go/cloudbuild.yaml
- go/go110/Dockerfile
- go/go112.yaml
- go/go112/Dockerfile
- go/go113.yaml
- go/go113/Dockerfile
- go/go114.yaml
- go/go114/Dockerfile
- go/go16/Dockerfile
- go/go18/Dockerfile
- go/go19/Dockerfile
The source of truth for these images is now GitHub!
> chore(go): move images off of GoB

- java/java10/Dockerfile
- java/java11/Dockerfile
- java/java7/Dockerfile
- java/java8/Dockerfile
- java/java9/Dockerfile
using debian instructions for installing docker
> fix(java): fix debian install for docker

- php/README.md
- php/cloudbuild-test.yaml
- php/cloudbuild.yaml
- php/php72/Dockerfile
- php/php73/Dockerfile
- php/php74/Dockerfile
Add the PHP dockerfiles used in [php-docs-samples](https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/.kokoro/docker)
Note: This is not related to the client libraries, only to the samples. Does that mean it doesn't really fit here?
> feat: add php

- node/10-user/Dockerfile
- node/12-user/Dockerfile
- node/14-user/Dockerfile
Installing docker in docker for node10, 12, 14
> chore(node): install docker on debian

- node/16-user/Dockerfile
- node/cloudbuild.yaml
**N.B:** I haven't tested this, as I'm not quite sure how to.
> chore(node): Add Node 16 image

- ruby/multi/Dockerfile
- dependencies needed for browser automation tests in recaptcha
> add chrome and chrome driver dependencies

- java/cloudbuild-test.yaml
- java/cloudbuild.yaml
- java/java17.yaml
- java/java17/Dockerfile
Generate Java 17 image. Part of https://github.com/GoogleCloudPlatform/java-docs-samples/issues/6197
> chore: generate Docker image for Java 17

- go/cloudbuild-test.yaml
- go/cloudbuild.yaml
- go/go115/Dockerfile
- go/go116/Dockerfile
- go/go119.yaml
- go/go119/Dockerfile
* Remove 1.11, 1.12, 1.13, 1.14 from `cloudbuild.yaml`.
b/241293582
> feat(go): add Go 1.19 image

- java/graalvm/Dockerfile
- java/graalvm17/Dockerfile
Reverts googleapis/testing-infra-docker#245
> Revert "chore: upgrade native images tests to 22.2.0"

- java/graalvm/Dockerfile
- java/graalvm17/Dockerfile
Install Terraform to GraalVM images.
> chore: Add terraform to graalvm dockerfile

- renovate.json
Tested via https://github.com/mpeddada1/renovate-bot-test/pull/6
> chore: manage native image docker image version through renovate bot

- node/14-puppeteer/Dockerfile
This should address:
```
ERROR: (gcloud.components.update) You cannot perform this action because you do not have permission to modify the Google Cloud SDK installation directory [/home/node/google-cloud-sdk].```
> build: activate pyenv in Dockerfile to update gcloud components

- php/php81/Dockerfile
Adding python3.9 and pip similar to [google-cloud-php-docs](https://github.com/googleapis/google-cloud-php/blob/main/.kokoro/docs/docker/Dockerfile#L100-L110)
> feat : Update PHP 8.1 docker image

- go/go119/Dockerfile
- go/go120/Dockerfile
- go/go121/Dockerfile
This is used by some storage emulator tests.
> fix(go): re-add docker

- java/cloudbuild.yaml
> chore: mark Java container image as 'infrastructure-public-image-'

- php/cloudbuild-test.yaml
- php/cloudbuild.yaml
- php/php80.yaml
- php/php81.yaml
- php/php82.yaml
Fixes https://github.com/googleapis/testing-infra-docker/issues/371
> fix: add php image tests

- java/graalvm/Dockerfile
- java/graalvm17/Dockerfile
- java/java11/Dockerfile
- java/java17/Dockerfile
- java/java21/Dockerfile
- java/java8/Dockerfile
Add xmlstarlet to modify xml files (specifically for pom.xml files).
> feat: Add xmlstarlet for Java docker images

- node/14-user/Dockerfile
- node/cloudbuild-test.yaml
Use the default python for gcloud CLI
Build the node14 image during presubmit to ensure it builds
> build: try to fix node14 image build

- ruby/multi/Dockerfile
Needed for an update to the release scripts.
> feat(ruby): Include gh cli in the Ruby image

- syft/Dockerfile
- syft/syft.yaml
Pre-install utilities to help build SBOMs during the release process
> feat: add jq, git, zip, uuidgen for sbom generation

- common/cloudbuild.yaml
> feat: Create a common cloudbuild.yaml to generate docker images

- common/cloudbuild.yaml
> feat: remove cache use from common/cloudbuild.yaml

- common/cloudbuild-structure-test.yaml
> feat: create cloudbuild yaml file with structure-test

- syft/airlock/Dockerfile
b/407529434#comment2
The file was based on syft/Dockerfile
> feat: create syft airlock dockerfile

- ruby/multi/Dockerfile
Details:
* Update Ubuntu to Noble (24.04)
* Update Ruby 3.4 version to 3.4.4
* Update Rubygems to 3.6.9
* Update Bundler to 2.6.9
* Update Node to 2.15.1
* Update GH to 2.72.0
* Removed two packages that seem unnecessary (and won't install) under Noble
* Removed deprecated installation steps from rbenv install
> feat(ruby): Update software in Ruby test image

- infrastructure/cloudbuild-test.yaml
- infrastructure/cloudbuild.yaml
- infrastructure/googleapis/prebuild.sh
Add ability to save prebuilt gapic-generator tarballs for ruby & PHP
Add ability to build googleapis image on code change.
Towards b/421929255
> feat: add prebuilt script for prebuilding gapic-generator tarballs
