- python/googleapis/python-multi/Dockerfile
Needed for testing Parquet serialization in the `google-cloud-bigquery` library.
> Add snappy compression library

- java/java11/Dockerfile
- java/java7/Dockerfile
- java/java8/Dockerfile
When trying to install a pip package like `gcp-docuploader`, you sometimes get `AttributeError: '_NamespacePath' object has no attribute 'sort'` which appears to be fixed by upgrading `pip` and `setuptools` [source](https://github.com/googleapis/google-cloud-python/issues/2990#issuecomment-283586901)
> Upgrade pip and setuptools on java images

- java/java7.yaml
- java/java7/Dockerfile
See https://github.com/docker-library/openjdk/issues/117#issuecomment-355139057
The latest openjdk:7-jdk is broken
> Pin java 7 to 1.7.0_151 which contains a fix for gradle

- python/cloud-devrel-kokoro-resources/python/Dockerfile
For some tests I am working on I need to use an updated gcloud sdk to access: `gcloud ai-platform` command.  It replaces `gcloud ml-engine` and exposed more flags such as `--python-version`.
I am open to building a separate image to be used in this set of tests if we are concerned that updating the gcloud version causes issues for other tests.
> update python Dockerfile to use CLOUD_SDK_VERSION 253.0.0

- node/10-user/Dockerfile
- node/11-user/Dockerfile
- node/12-user/Dockerfile
This is a step toward https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1436.
An alternative to adding graphviz to the container is to pursue container-centric unit testing for Cloud Run on node.js as a follow-up to #16
> node: add graphviz to container image

- ruby/autosynth/Dockerfile
- ruby/ruby-multi/Dockerfile
- ruby/ruby-release/Dockerfile
General update for runtimes and key libraries in the various Ruby images.
* Ruby -> 2.6.5
* Python 3.6.x -> 3.6.9
* Node -> 10.16.3
* Install both bundler 1.17.3 and 2.0.2 to support both gemfile formats
* In the image used to test libraries against multiple Ruby versions, remove the Ruby 2.3 because it is EOL, and update Ruby 2.4, 2.5, and 2.6 to the latest patch release of each.
> chore(ruby): Update runtime versions in Ruby images

- java/java11/Dockerfile
For sample https://github.com/GoogleCloudPlatform/java-docs-samples/pull/1610
Reference node PR #31
> java: add graphviz to container image

- java/java11/Dockerfile
When I built this locally I didn't recognize that it failed...
Moving it to after the python install, now builds.
> java: Fix failing build

- elixir/Dockerfile
- elixir/cloudbuild.yaml
- elixir/elixir14.yaml
- elixir/elixir15.yaml
- elixir/elixir17.yaml
- elixir/elixir18.yaml
- elixir/elixir19.yaml
* Add Elixir 1.8 and 1.9 images
* Update Nodejs and Docker to the latest LTS
* Fix the Dockerfile so it can still build PLTs if there is no current cache
* Dockerfiles use their own copies of `plt_builder` instead of sharing the `/workspace` copy, to prevent collisions when Cloud Build builds them simultaneously.
> Update Elixir images

- node/10-user/Dockerfile
- node/12-user/Dockerfile
- node/8-user/Dockerfile
We want to start using Kokoro for testing gapic-generator-typescript, and `protoc` is one of its dependencies. I can imagine that having it in the images won't hurt.
(I will appreciate your help with pushing the new images to gcr.io, I have no idea how to do it :) )
> feat: add protoc to node Docker images

- python/googleapis/python-multi/Dockerfile
Updates OpenPGP Public Keys based on fingerprints published at
https://www.python.org/downloads/ Double-checked locally via
```
docker build -t python-multi ./python/googleapis/python-multi > log.txt
```
and
```
grep -C 3 fingerprint log.txt
```
Output:
```
$ grep -C 4 fingerprint log.txt
gpg:                 aka "Benjamin Peterson"
gpg:                 aka "Benjamin Peterson"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: C01E 1CAD 5EA2 C4F0 B8E3  5715 04C3 67C2 18AD D4FF
+ rm -r /tmp/tmp.eCQGdKJjRC python-2.7.17.tar.xz.asc
+ mkdir -p /usr/src/python-2.7.17
+ tar -xJC /usr/src/python-2.7.17 --strip-components=1 -f python-2.7.17.tar.xz
+ rm python-2.7.17.tar.xz
--
-- …
```
> feat!: add Python 3.8, drop Python 3.3

- python/cloud-devrel-kokoro-resources/python/Dockerfile
Required to run tests for this Sample: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2554
> Updating to install graphviz

- node/12-puppeteer/Dockerfile
- node/cloudbuild.yaml
Allows us to use newer versions of Node.js in browser testing.
> feat: Node 12 container for running puppeteer

- python/cloud-devrel-kokoro-resources/python/Dockerfile
This will make it easier to scan for existing packages and determine where to place addition packages in the future.
Aside: In order to build the protobuf docs, I considered adding the [protobuf-compiler package](https://packages.ubuntu.com/xenial/protobuf-compiler), but it's quite out-of-date in Ubuntu 16.04. I'll follow-up with a second image with C++ build tools available, instead.
> refactor(python): alphabetize package list

- python/cloudbuild.yaml
The kokoro builds I triggered after #51 and #52 succeeded but the images did not have 2.7. (This is most likely unrelated to the Dockerfile changes made in those two PRs).
Locally I tried a clean build with --no-cache, and all the specified Python versions were present.
We can remove the `--no-cache` once the latest images are in a good state.
> fix(python): use --no-cache so images are built from scratch

- python/googleapis/python-multi/Dockerfile
Some samples need PyAudio, which requires portaudio19-dev. https://people.csail.mit.edu/hubert/pyaudio/
https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2628
> feat(python): add portaudio19-dev dependency for PyAudio

- java/java11/Dockerfile
Required for [`functions/imagemagick` samples](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/2520)
(Currently they're only running on Java 11.)
> Add imagemagick package

- elixir/cloudbuild.yaml
- go/cloudbuild.yaml
- java/cloudbuild.yaml
- node/cloudbuild.yaml
- python/cloudbuild.yaml
- ruby/cloudbuild.yaml
Actually tested this time with `gcloud builds submit --config python/cloudbuild.yaml .` 😅 
On the bright side all the triggers seem to have been setup correctly https://github.com/googleapis/testing-infra-docker/commit/c1b64b41139e4069a64fa5b030c729ad797eac68
> fix: correct syntax in cloudbuild.yaml files

- java/java7/Dockerfile
Should fixes: 
```
Step #0 - "java7-build": 17 upgraded, 102 newly installed, 0 to remove and 88 not upgraded.
Step #0 - "java7-build": Need to get 76.6 MB of archives.
Step #0 - "java7-build": After this operation, 278 MB of additional disk space will be used.
Step #0 - "java7-build": WARNING: The following packages cannot be authenticated!
Step #0 - "java7-build":   ncurses-bin libtinfo5 libncursesw5 libncurses5 libpipeline1 libisl10
Step #0 - "java7-build":   libcloog-isl4 libfontenc1 libmpfr4 libtcl8.6 libxft2 libxss1 libtk8.6
Step #0 - "java7-build":   libxmu6 libxaw7 libxcb-shape0 libxmuu1 libxv1 libxxf86dga1 libmpc3
Step #0 - "java7-build":   init-system-helpers manpages binfmt-support binutils cpp gcc g++ make
Step #0 - "java7-build":   libtimedate-perl libdpkg-perl dpkg-dev …
```
> fix(java): use --force-yes on apt-get install for java 7

- java/cloudbuild.yaml
At some point, cloudbuild started running from the root of the project, not from the location of the cloudbuild.yaml. Thus we need to specify the structure_test yaml path as java/java[version].yaml.
I actually ran this one and it completed successfully. Note that my IDE reformatted the yaml file with `prettier`
> fix(java): fix paths to structure_test yaml configs

- ruby/cloudbuild.yaml
The canonical Ruby images are actually elsewhere, in https://github.com/googleapis/google-cloud-ruby. The images currently in testing-infra-docker are out of date and can break Ruby CI if they are built. Disable upload of these images for now to prevent that. We still need to figure out how to reconcile the two sets of images.
> fix: Disable build of the Ruby images

- renovate.json
This will prevent PRs like #57. We don't want to upgrade the Go version in the testing images.
> chore: ignore Go Dockerfile Renovate updates

- node/12-puppeteer/Dockerfile
After some unknown change headless Chrome now requires `libXss1.so.1`. Let's add it into our browser testing Docker image.
@busunkim96 or @bcoe, after this one is merged, I will need your folks' help in deploying this updated image :)  I don't think I have access to that gcr.io project. Thank you!
> fix: add libxss1 for Chrome

- node/12-puppeteer/Dockerfile
Apparently it now needs this one as well.
```
02 09 2020 17:25:49.233:ERROR [launcher]: ChromeHeadless stdout: 
02 09 2020 17:25:49.233:ERROR [launcher]: ChromeHeadless stderr: /tmpfs/src/github/gax-nodejs/node_modules/puppeteer/.local-chromium/linux-782078/chrome-linux/chrome: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory
```
I hope this is the last one, but let's see :)
> fix: add libxtst6 for Chrome

- .kokoro/sync-triggers.sh
- cloudbuild.yaml
New commits to master will trigger a new cloudbuild job that will sync other cloudbuild triggers by finding other cloudbuild.yaml files in the directory.
This approach was pioneered in the repo-automation-bots project to automatically deploy new bots.
> build: automatically register new cloudbuild triggers

- ruby/multi/Dockerfile
- ruby/windows/Dockerfile
The bashrc in the ruby-multi image was erroring when attempting to initialize pyenv. Apparently, `-e` is not available in the built-in `echo` available in the image, but I don't think the conditional is necessary anyway.
Also, update Ruby 2.7 installation to 2.7.2, and disable documentation building when installing bundler on windows.
> fix(ruby): Fix python installation in Ruby autosynth image

- ruby/multi/Dockerfile
ruby-docs-samples uses memcached in its ci flow
> chore(ruby): install memcached

- ruby/multi/Dockerfile
Trampoline V2 runs scripts as an unprivileged user. However, the Ruby image installs a bunch of things (notably including Ruby itself) into `/root` which is by default unreadable by any user except root. We'll loosen that a bit and allow other users to read and navigate into that directory, to make the image usable by Trampoline V2.
> fix(ruby): Make root readable so Trampoline V2 jobs can use it

- go/go116/Dockerfile
Changes: 
- Use pyenv to install python 3.8 instead of defaulting to version 3.7 by using apt-get
Motivation: 
- I'm using go116 to run a test suite built in Python that depends on Python version 3.8
Open to suggestions on how to do this the right way.
> chore: update Python version from 3.7 to 3.8

- go/go116/Dockerfile
Problem: 
Our nox test suite for google-cloud-go/logging currently requires Python 3.7, and will require Python 3.8 shortly. See [test suite](https://github.com/googleapis/env-tests-logging)
Solution: 
This PR installs latest versions for Python & pip in `3.7` and `3.8` via the `pyenv` util. It defaults to version 3.8. 
Though in the container, users can chose which version to use by: `pyenv global VERSION`. 
This installation step now takes ~3 minutes (tried it locally). 
The alternative to this PR is that I revert #125 to just install python 3.7 by default, but I'll still need Python3.8 in this image at some point in the near future. Open to suggestions!
> chore(go): install both python v3.7 and 3.8 in go116

- go/go115/Dockerfile
- go/go116/Dockerfile
Splitting up making these changes to go versions to avoid gcbrun timeout
Changes:
- Add pyenv flexible python version manager to all go images (not just go116 previously)
-  Add docker in test images for all versions
-  Clean up large file after apt-get update, run apt-update only once, as an optimization
Reason: 
I need docker and docker-cli in environment tests. And it seems to be an open issue [here](https://github.com/googleapis/testing-infra-docker/issues/16). This docker-in-docker feature currently exists for go image with [Java](https://github.com/googleapis/testing-infra-docker/blob/5ac625a7949d71846c1ea9306fe4267ae5abe0ba/java/java11/Dockerfile#L85), [Python](https://github.com/googleapis/testing-infra-docker/blob/5ac625a7949d71846c1ea9306fe4267ae5abe0ba/python/googleapis/python-m …
> chore: add docker to go115 and go116

- go/cloudbuild.yaml
Fixes: failed CloudRun release for Go: https://github.com/googleapis/testing-infra-docker/runs/2290139583
It finished building 115, then timed out before completing go116
Increasing timeout from 1 hour to 2 hours, similar to Python, Ruby, etc.
> chore(go): increase Go build timeout to 2 hours

- ruby/multi/Dockerfile
Sets `$OLDEST_RUBY_VERSION`, `$NEWEST_RUBY_VERSION` which are used by CI scripts in google-cloud-ruby to decide "semantically" which Ruby versions to use. Also sets `$RBENV_ROOT`, `$PYENV_ROOT`, and `$NODENV_ROOT` which are needed to run those languages as a nonprivileged user.
> fix(ruby): Set additional environment variables for Ruby CI

- java/cloudbuild-test.yaml
- java/cloudbuild.yaml
- java/java11.yaml
- java/java11/Dockerfile
- java/java8.yaml
- java/java8/Dockerfile
Some python tools are breaking because we're using a super old version of python 3.6.x and a `typing` type was added in a patch version of python.
> fix(java): upgrade python from 3.6.1 to 3.6.12, stop building non-LTS java versions

- go/go111/Dockerfile
- go/go112/Dockerfile
Similar to #129, adding conformance to other go images. Submitting as separate PRs to avoid presubmit timeout
Note: I actually don't use these images for our tests, but figured we wanted parity among all image versions
> chore(go): add pyenv and docker to go111 go112

- php/php74/Dockerfile
- php/php80/Dockerfile
There are `pecl` errors for PHP 7.4 and 8.0 due to `pecl` not being compiled by default in those versions.
I am moving the pecl install into the PHP compilation, and moving the PHP purge up a step
> php: move apt purge and add --with-pear flag

- go/go111/Dockerfile
- go/go112/Dockerfile
- go/go113/Dockerfile
- go/go114/Dockerfile
- go/go115/Dockerfile
- go/go116/Dockerfile
Updates: https://github.com/googleapis/google-cloud-go/issues/4061
> feat(go): add testing deps to images

- go/go113/Dockerfile
- go/go114/Dockerfile
- go/go115/Dockerfile
- go/go116/Dockerfile
Fix go dockerfile build issues [(1)](https://pantheon.corp.google.com/cloud-build/builds;region=global/b8a0eb35-83de-490d-b59e-be11f8554946;step=10?project=cloud-devrel-kokoro-resources)[(2)](https://pantheon.corp.google.com/cloud-build/builds/fc284550-9a51-4909-82c7-3bd1fdf5b898;step=4?project=cloud-devrel-kokoro-resources)
- update `python-openssl` to `python3-openssl` in go116
- revise go113, go114, go115 dockerfile commands
```
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package python-openssl
```
```
go: cannot use path@version syntax in GOPATH mode
The command '/bin/sh -c GO111MODULE=on go get honnef.co/go/tools/cmd/staticcheck@latest &&     go get github.com/jstemmer/go-junit-report@latest' returned a non-zero code: 1
```
> fix(go): fix go dockerfile build issues

- php/README.md
- php/cloudbuild-test.yaml
- php/cloudbuild.yaml
- php/php/Dockerfile
For improved testing in PHP samples, we want to use one container which allows switching between PHP versions. This will allow the following improvements:
1. The samples can run in parallel for each sample directory, instead of for each PHP version. This means each kokoro instance will run This should speed up running tests significantly, as the time to run the tests of the longest sample directory 3 times should be less than the time required to run the entire sample suite.
2. We currently use 7 different Cloud Projects to run our tests: Each of the three supported versions of PHP we test on require one Cloud Project for firestore and one for datastore, plus one default Cloud Project. This is required to avoid race conditions. With this change, we will only need 2 Cloud Projects total, …
> feat: add php container which contains all currently supported versions

- java/graalvm/Dockerfile
This PR upgrades the GraalVM version 22.0.02 (the latest). 
The latest version of the native-maven-plugin (0.9.11) which is used to run tests with native image support is incompatible with GraalVM 21.2.0. As a result, we're running into the following error in all our repos:
```
[org.graalvm.junit.platform.NativeImageJUnitLauncher:950181]    classlist:     862.05 ms,  0.96 GB
Error: Main entry point class '@/tmp/native-image6785363509462544469args' not found.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
```
Reproducer: https://github.com/mpeddada1/native-image-args 
cc @meltsufin
> fix: upgrade GraalVM version to 22.0.0

- java/graalvm.yaml
- java/graalvm/Dockerfile
Storage tests require docker to be installed and on $PATH, otherwise the result in the following error
```
java.io.IOException: Cannot run program "docker": error=2, No such file or directory
Caused by: java.io.IOException: error=2, No such file or directory
```
> fix: install docker on Native Image testing Kokoro image

- java/java17/Dockerfile
This mimics the Java 11 image:
https://github.com/googleapis/testing-infra-docker/blob/c186d708c19c3b3bcfd2a0d4c9f85bc4a7b832cf/java/java11/Dockerfile#L75-L83
> feat: Update Java 17 image with sample dependencies

- java/java8/Dockerfile
This change enables us to build a project in JDK 11 and run tests in JDK 8 runtime.
How I confirmed the updated Docker file:
```
suztomo@suztomo:~/testing-infra-docker/java/java8$ docker build .
Sending build context to Docker daemon  6.144kB
Step 1/20 : FROM openjdk:8-jdk
---> c43167b660ad
...
Step 20/20 : WORKDIR /workspace
---> Running in 949d7b16df43
Removing intermediate container 949d7b16df43
---> 890bb1639e37
Successfully built 890bb1639e37
suztomo@suztomo:~/testing-infra-docker/java/java8$ docker run --rm -it --entrypoint bash 890bb1639e37
root@d2439762fd1a:/workspace# printenv
PYENV_SHELL=bash
HOSTNAME=d2439762fd1a
JAVA_HOME=/usr/local/openjdk-8
JAVA8_HOME=/usr/local/openjdk-8
PWD=/workspace
HOME=/root
LANG=C.UTF-8
JAVA11_HOME=/usr/lib/jvm/java-11-openjdk-amd64
TERM=xterm
SHLVL=1 …
```
> deps: adding JDK 11 as the supplement to java8 container

- ruby/multi/Dockerfile
Changes:
* Add Ruby 3.1 to the list of versions installed.
* Update all Rubies to their latest patchlevel
* Advanced `OLDEST_RUBY_VERSION` to 2.6, `NEWEST_RUBY_VERSION` to 3.1, and `DEFAULT_RUBY_VERSION` to 3.0.
* Provided dedicated constants for the current patchlevel for each minor Ruby release, so that tests can select for them (e.g. a runtime test that needs a specific minor release).
* Updated Ubuntu to focal (20.4)
* Added libvips for Rails 7
* Dropped Bundler 1 since it doesn't work with newer Rubies
* Installed Ubuntu-focal version of docker
* Updated Python to 3.9.13 and Node to 16.15.0.
> feat(ruby): Update Ruby versions

- java/java11/Dockerfile
- java/java11014/Dockerfile
- java/java17/Dockerfile
- java/java8/Dockerfile
fix(java): fix debian install for Terraform  
Will be used in: GoogleCloudPlatform/java-docs-samples/tree/main/bigtable/
> fix(java): fix debian install for Terraform  cla: yes

- java/java11.yaml
- java/java11/Dockerfile
- java/java17.yaml
- java/java17/Dockerfile
- java/java8.yaml
- java/java8/Dockerfile
[WIP]
I'm not sure if there is any historical reason why we're using python v3.6.x. Opening a draft PR to start a discussion to migrate/ upgrade the current python version `v3.6.x` to a non-EOL python version `v3.7.x+`. I'd like to aim for at least Python `v3.9.13`
- Info via https://devguide.python.org/versions/
Issues with Python v3.6.x:
- It has reached EOL almost a year ago
- gcp-docuploader (https://github.com/googleapis/docuploader) has to be pinned at v0.6.3 (docuploader v0.6.4+ has dependencies that aren't compatible with Python v3.6.x).
Confirmation before release:
Logs:
Owl-bot: https://github.com/googleapis/testing-infra-docker/pull/260#issuecomment-1358329724
GCP-DocUploader:
```
lawrenceqiu@lawrenceqiu:~/IdeaProjects/google-cloud-java$ python3 --version
Python 3.9.0 …
```
> chore: Upgrade to Python 3.9.13 for all Java Containers

- renovate.json
GraalVM 22.3.1 has been released but a renovate-bot PR is yet to be created in this repository. 
From https://github.com/googleapis/testing-infra-docker/issues/162:
This PR sets depNameTemplate to `ghcr.io/graalvm/graalvm-ce` instead of `jdk`. Tested with https://github.com/mpeddada1/renovate-bot-test/pull/12/files
> fix(java): ensure that renovate-bot picks up graalvm-ce docker image tag

- node/14-puppeteer/Dockerfile
- node/cloudbuild-test.yaml
- node/cloudbuild.yaml
Moving the Cloud SDK installation below setting the user, to match the `node14:user` Dockerfile flow.
This should address:
```
ERROR: (gcloud.components.update) You cannot perform this action because you do not have permission to modify the Google Cloud SDK installation directory [/home/node/google-cloud-sdk].
```
> build: add puppeteer-14 to test workflow

- node/10-user/Dockerfile
- node/12-user/Dockerfile
- node/14-puppeteer/Dockerfile
- node/14-user/Dockerfile
- node/16-user/Dockerfile
Stretch is EOL, let's use Buster, and also bump the version of Google Cloud SDK to the latest one.
> build: use Debian buster for Node 16 image

- ruby/multi/Dockerfile
Adding qt5-qmake for ruby docs samples.
It will replace poltergiest (which is deprecated) with cuprite which uses qmake
> chore: added qt5-qmake dependency for ruby docs samples

- java/README.md
- java/cloudbuild.yaml
- java/java21.yaml
- java/java21/Dockerfile
Add configuration files to build a new trampoline image for Java 21 runtime.
Makes a small fix to java/README file to reflect that the client libraries support at least Java 8 runtime.
> chore(proc): Add trampoline image config for Java 21

- elixir/Dockerfile
- elixir/README.md
- elixir/cloudbuild-test.yaml
- elixir/cloudbuild.yaml
- elixir/elixir110.yaml
- elixir/elixir111.yaml
- elixir/elixir112.yaml
- elixir/elixir113.yaml
- elixir/elixir114.yaml
- elixir/elixir115.yaml
- elixir/elixir116.yaml
- elixir/elixir16.yaml
- elixir/elixir17.yaml
- elixir/elixir18.yaml
- elixir/plt_builder/mix.exs
For now just getting it to rebuild Elixir 1.12-1.16 which are the upstream supported versions and the ones I really need. Earlier versions are commented out of the configs for the moment because Cloud Build seems to be running out of resources if it tries to build too many. (Dialyzer and PLT generation does take a considerable amount of memory.) Although I think I'll still want to build the rest of them later so we have them, so I'm not deleting those configs outright.
> feat: Updated elixir images to include newer elixir versions

- java/cloudbuild.yaml
Using `$SHORT_SHA`, we can ensure the tags are unique https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#using_default_substitutions
> chore: use unique 'infrastructure-public-image-' tags for Java

- ruby/multi/Dockerfile
Tests that use selenium are currently failing due to chrome refusing to start. When checking the image manually, it looks like chrome couldn't find `libasound.so.2`, so we'll see if installing that library fixes things.
> fix(ruby): install libasound2 for chrome

- php/cloudbuild.yaml
1. Update `gcr.io/cloud-devrel-kokoro-resources/php*` images to `gcr.io/cloud-devrel-public-resources/php80'`
2. This is in line with what Ruby does [here](https://github.com/googleapis/testing-infra-docker/blob/b7a0602daaf192f38b138dcc4ed22d354d3241be/ruby/cloudbuild.yaml#L46)
3. PHP has images exposed via [`cloud-devrel-public-resources`](https://pantheon.corp.google.com/gcr/images/cloud-devrel-public-resources) till php74, but not for later versions.
[b/331742181](http://b/331742181) This significantly speeds up development, because `cloud-devrel-kokoro-resources` images are not accessible to many developers within cloud sdk
> fix: update php docker testing images to public buckets

- php/php81/Dockerfile
Following changes are being made:
1. Adding sodium extension to php81 docker, which is required by dependencies
2. Removing unrecognized options of php's `configure` which are flagged as warnings in docker build, they show up [here](https://paste.googleplex.com/5054788078665728#l=354).
3. Enabling the extension in `php.ini` config
[b/331742181](http://b/331742181)
> fix: add sodium extension for php81

- php/php80.yaml
- php/php80/Dockerfile
- php/php81.yaml
- php/php82.yaml
Adding [version number](https://pecl.php.net/package/pdo_sqlsrv/5.11.1) for a relatively sparingly php extension `pdp_sqlsrv`.
Currently, since there's is no version of `pdo_sqlsrv`, it fetches latest which is not supported on php8.0 everytime php process loads it emits a warning like below:
```
root@9e9dd96a511f:/# php -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_sqlsrv.so' (tried: /opt/php80/lib/php/extensions/no-debug-non-zts-20200930/pdo_sqlsrv.so (/opt/php80/lib/php/extensions/no-debug-non-zts-20200930/pdo_sqlsrv.so: cannot open shared object file: No such file or directory), /opt/php80/lib/php/extensions/no-debug-non-zts-20200930/pdo_sqlsrv.so.so (/opt/php80/lib/php/extensions/no-debug-non-zts-20200930/pdo_sqlsrv.so.so: cannot open shared object file: No such …
```
> fix: add pdo_sqlsrv version to avoid php warnings

- php/README.md
- php/cloudbuild-test.yaml
- php/cloudbuild.yaml
- php/php82/Dockerfile
- php/php83.yaml
- php/php83/Dockerfile
PHP 8.0 is EOL, and PHP 8.3 was released over 6 months ago. We should remove the PHP 8 container and begin testing on PHP 8.3
See https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1963
> feat: remove php 8.0, add php 8.3

- node/18-user/Dockerfile
- node/cloudbuild-test.yaml
- node/cloudbuild.yaml
chore: stop building node < 18 (EoL)
> chore: force rebuild of node 18 image

- go/cloudbuild-test.yaml
- go/cloudbuild.yaml
- go/go121/Dockerfile
- go/go122/Dockerfile
- go/go123.yaml
- go/go123/Dockerfile
Note: we need to set toolchain to auto just for installing tools. We want to keep the image default of local for CI and fail if a dependency tries to update the go version.
Ref: https://github.com/docker-library/golang/issues/472
> feat(go): add Go 1.23 support

- go/go121/Dockerfile
- go/go122/Dockerfile
- go/go123/Dockerfile
Create a sub-shell and export the envvar to apply to all commands.
Noticed in #398
> fix(go): apply GOTOOLCHAIN to all subcommands

- node/14-user/Dockerfile
- node/cloudbuild-release.yaml
- ruby/cloudbuild-release.yaml
- Updated python version to match Node 18 (existing version for node 14 was no longer supported by gcloud)
- Renamed node release image to release image convention language + version
> fix(node): update python version for node14 and release image name

- node/18-user/Dockerfile
The installed version of `npm` has a few bugs. This will ensure the build is on a newer version of `npm` along with disabling the npm update check.
> chore(node): Setup `npm` on Node 18

- node/18-user/Dockerfile
Looking at this build, we can see `.npm-global` is being created as `root` rather than user `node`:
- commit: https://github.com/googleapis/gaxios/pull/669/commits/f37b01bf6e4e00979d35e0850f0b234e0a13ced7
- log: https://btx.cloud.google.com/invocations/d53cfd6a-e9f7-4ec7-a800-63f9094cb782/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Fpresubmit%2Fgoogleapis%2Fgaxios%2Fnode18%2Fsamples-test/log
This is causing access errors downstream, as `kbuilder` cannot access this directory and fails.
> ci: run `npm` config as `User: node`

- .github/CODEOWNERS
> chore(codeowners): Update the ruby codeowner to the teamsync-managed team

- java/java17.yaml
- java/java17/Dockerfile
Java 17 container image to use Maven 3.9.9 from Airlock repository. The new Maven version addresses missing dependency problems (b/383221175#comment18).
> deps: java17 to use Maven 3.9.9 from Airlock

- java/java17/Dockerfile
- java/java8.yaml
- java/java8/Dockerfile
Applying https://github.com/googleapis/testing-infra-docker/pull/430 to java8 container image too. After this, I'll need to update the apt-get commands to source Airlock.
The remaining java11 and java21, and java11014 are not in scope of the change we need to use for Airlock.
> deps: java8 to use Maven 3.9.9 from Airlock

- ruby/multi/Dockerfile
In particular, we want to vendor `gems` and `jwt` in the image so the release job doesn't have to install them just-in-time.
Details:
* Removed Ruby 2.7
* Added Ruby 3.4
* Vendored the `gems` and `jwt` gems.
* Bumped bundler to 2.5.23.
* Bumped python to 3.10.16.
* Bumped nodejs to 18.20.6.
* Deprecated the separate `BUNDLER1_VERSION` and `BUNDLER2_VERSION` envs.
> feat(ruby): Bump versions and vendor additional gems

- syft/Dockerfile
- syft/cloudbuild-release.yaml
- syft/cloudbuild-test.yaml
- syft/syft.yaml
We may need to run `syft` during releases so we maintain our own docker image with a specific `syft` version installed.
> feat: add syft release image

- ruby/multi/Dockerfile
I'm getting intermittent JWT signature validation errors using 2.38.0 when running docuploader. Trying to verify whether it's a regression in google_auth.
> fix(ruby): Pin google_auth pip package to 2.37.0

- ruby/cloudbuild-release.yaml
- ruby/cloudbuild-test.yaml
- ruby/release.yaml
- ruby/release/Dockerfile
Creates a new ruby-release image based on the logic of the ruby-multi image with a few differences:
* only includes the default version of ruby (currently 3.3), but still sets relevant env vars for min/max/default
* does not include chrome or nodejs which is used for testing and compiling assets
* adds syft binary
* add gcloud CLI binary
> feat: create ruby release image

- php/cloudbuild-release.yaml
- php/cloudbuild-test.yaml
- php/release.yaml
- php/release/Dockerfile
This image includes uuid-runtime for SBOM generation.
This image is based on the php-81 image which is currently used for releases (and tests). Tests do not need additional dependencies.
> feat: create dedicated php-release image

- java/cloudbuild-release.yaml
- java/cloudbuild-test.yaml
- java/cloudbuild.yaml
- java/java8-airlock/Dockerfile
- java/java8.yaml
- java/java8/Dockerfile
Creating a separate Dockerfile for Airlock-confirmation to avoid disruption in releases. I reverted java/java8/Dockerfile and java/cloudbuild.yaml to the state before https://github.com/googleapis/testing-infra-docker/pull/435.
The "--load" was missing in the "docker buildx" command in the previous commit in java/cloudbuild-release.yaml. This resulted in Cloud Build not uploading the container image to Artifact Registry.
> chore: create java8-airlock container image in the release project

- syft/Dockerfile
- syft/syft.yaml
SBOM release scripts (golang) may need access to curl
> feat: add curl to syft image

- go/go124-release.yaml
- go/go124-release/Dockerfile
uuidgen is needed for SBOM generation
test: add assertions that `zip` and `git` are also installed
> feat: add uuid tools to go release image

- ruby/multi/Dockerfile
- ruby/release.yaml
- ruby/release/Dockerfile
The Ruby release script has reimplemented docuploader using a few lines of Ruby and a call to gcloud, and no longer needs Python or the gcp_docuploader package. In the new release image, I removed both, but I left Python itself in the multi image used for testing because I haven't yet verified that none of the tests (especially those in ruby-docs-samples) use Python for anything else.
Also removed a few debian packages from the release image that I'm pretty confident are never needed for releases, and updated various things to the latest versions.
> fix(ruby): Remove no several longer needed packages from Ruby release image, including the Python installation

- java/cloudbuild-test.yaml
- java/java8-airlock.yaml
- java/java8-airlock/Dockerfile
Terraform and Docker are not needed for the release jobs. cl/734604020
b/356854847
> fix: java8-airlock stop installing Terraform and Docker

- java/java8-airlock/Dockerfile
b/390675031#comment5. I uploaded the google-play-services in our 1P Artifact Registry repository. The step for google-play-services is no longer needed.
> deps: java8-airlock to stop installing google-play-services

- ruby/multi/Dockerfile
Identified in https://github.com/GoogleCloudPlatform/ruby-docs-samples/issues/1553
Internal b/410431197
[rubygems-update 3.5.4](https://togithub.com/rubygems/rubygems/releases/tag/v3.5.4) introduced a fix to ensure the ruby version constraints are adhered to when running `gem update --system`. This version of rubygems-update isn't made available in the ruby source (used by rbenv) until Ruby 3.3.1(the next Ruby release after this update)
This change ensures that the gem used to run `gem update --system` is updated to at least a version that considers Ruby versions before updating to the most _valid_ up to date version. 
Without this change, trying to build ruby images where the latest rubygems-updates drops ruby support will silently fail (due to the `gem update --system` failing in a for …
> set minimum rubygems-update to ensure gem update --system runs when ruby version deprecated

- java/java11/Dockerfile
- java/java17/Dockerfile
- java/java21/Dockerfile
- java/java8-airlock/Dockerfile
- java/java8/Dockerfile
The Central Portal API uses a bundle format, which is a zip file.
> fix(java): the Java containers to have zip for bundle files 

- syft/airlock/cloudbuild.yaml
b/407529434#comment4
Referenced https://github.com/googleapis/testing-infra-docker/blob/main/java/cloudbuild-release.yaml#L21 that @suztomo pointed out.
> feat: add cloudbuild for syft airlock image

- ruby/cloudbuild-release.yaml
- ruby/release.yaml
- ruby/release/.toys.rb
- ruby/release/Dockerfile
Previously, the Ruby release scripts would need to download three pieces of software from the internet during the release process: The release scripts (downloaded from https://github.com/googleapis/ruby-common-tools), and the gems `yard` and `redcarpet`. The primary purpose of this update is to vendor these items into the image itself, to reduce the risk of getting bad software, and to reduce release failures due to failure of those downloads. See internal issue b/417281463.
Details:
* Updated Ubuntu to Noble (24.04)
* Updated Ruby to 3.4.4
* Updated RubyGems to 3.6.9
* Updated Bundler to 2.6.9
* Updated GH to 2.72.0
* Installed Yard 0.9.37 into the image
* Installed Redcarpet 3.6.1 into the image
* Cloned ruby-common-tools into the image to bring in the release scripts
* Removed a bunch …
> feat(ruby): Include release scripts in Ruby release image

- elixir/cloudbuild-container-build-test.yaml
_CONTAINER_STRUCTURE_TEST_CONFIG is the parameter that's passed.
> fix: update parameter name for container test config

- node/18-user/Dockerfile
In order to resolves issues updating the version of gapic-showcase used in node gax, I am updating this image. [Context](https://yaqs.corp.google.com/eng/q/8562340148677705728) (internal-only link)
**Updates that MUST stay to fix thing**
- updating the debian version (though I think we can go to one prior and still be OK)
- updating the way we install docker (this is just in line with the latest docker instructions)
- switching the name of the package to `python3-ssl`
**Updates I'm open to reverting, I just updated while I was in there**
- updating the python version
- updating the gcloud version
Full disclosure: When I ran the test-application locally it passed, but I could not successfully run the system-tests locally for gax because I couldn't locally get the secrets populated properly
> fix: update node18-user to Debian bookworm

- node/18-user/Dockerfile
- node/cloudbuild-test.yaml
- node/node18.yaml
Most other release containers include the `jq` CLI to handle json parsing
This also adds a test to ensure the container contains the expected build tools
> build: include jq in node release image

- .github/CODEOWNERS
Cleaning up permissions, migrate ownership to cloud-sdk-go-eng
> chore: update go CODEOWNERS
